using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using HQ.Models.Helpers;

namespace HQ.Plugins.HeadlessBrowser.Models;

/// <summary>
/// Per-tool argument types. Each is the single source of truth for both the LLM-facing schema
/// (generated by <c>ToolSchemaGenerator</c> from these properties/attributes) and the runtime
/// binding target. Camel-cased property names match the LLM-facing parameter names.
/// </summary>

/// <summary>Args for tools that take no LLM parameters (advertises an empty object schema).</summary>
public class EmptyArgs;

public class NavigateToUrlArgs
{
    [Required]
    [Description("The URL to navigate to")]
    public string Url { get; set; }
}

public class GetPageContentArgs
{
    [Description("CSS selector for a specific element (optional)")]
    public string Selector { get; set; }

    [Description("'aria' (default), 'compressed' (clean DOM), 'text', or 'html'")]
    public string Format { get; set; }

    [Description("Filter hint: 'form_fill', 'navigation', 'data_extraction', 'search', or 'general' (default)")]
    public string TaskHint { get; set; }

    [Description("Maximum content length (default 50000 for text/html, 300 lines for aria)")]
    public int? MaxLength { get; set; }

    /// <summary>Legacy alias read by the tool body as a fallback for Format. Not advertised to the LLM.</summary>
    [Injected]
    public string ContentType { get; set; }
}

public class GetInteractiveElementsArgs
{
    [Description("Filter: 'links', 'buttons', 'inputs', 'all' (default 'all')")]
    public string ElementType { get; set; }

    [Description("Scope search within this CSS selector")]
    public string Selector { get; set; }

    [Description("'aria' (default, from accessibility tree) or 'legacy' (CSS selectors via DOM walk)")]
    public string Format { get; set; }
}

public class SearchPageArgs
{
    [Required]
    [Description("Text to search for (case-insensitive)")]
    public string Query { get; set; }
}

public class GetElementArgs
{
    [Required]
    [Description("Ref ID to expand (e.g. 'e5')")]
    public string Ref { get; set; }
}

public class GetVisibleTextArgs
{
    [Description("Maximum text length (default 10000)")]
    public int? MaxLength { get; set; }
}

public class ClickElementArgs
{
    [Description("Ref ID from page snapshot (e.g. 'e5'). Preferred over selector.")]
    public string Ref { get; set; }

    [Description("CSS selector (fallback if ref not available)")]
    public string Selector { get; set; }

    [Description("Return only what changed after the click (default false)")]
    public bool? DiffMode { get; set; }
}

public class FillFieldArgs
{
    [Description("Ref ID from page snapshot (e.g. 'e3'). Preferred over selector.")]
    public string Ref { get; set; }

    [Description("CSS selector (fallback if ref not available)")]
    public string Selector { get; set; }

    [Required]
    [Description("The value to type into the field")]
    public string Value { get; set; }
}

public class SubmitFormArgs
{
    [Description("Ref ID of the submit button (e.g. 'e7'). Preferred over selector.")]
    public string Ref { get; set; }

    [Description("CSS selector of the submit button or form element")]
    public string Selector { get; set; }

    [Description("Return only what changed after submit (default false)")]
    public bool? DiffMode { get; set; }
}

public class TakeScreenshotArgs
{
    [Description("Custom file name for the screenshot (optional, defaults to timestamp)")]
    public string FileName { get; set; }

    [Description("Capture the full scrollable page (default false)")]
    public bool? FullPage { get; set; }

    [Description("CSS selector to screenshot a specific element instead of the full page")]
    public string Selector { get; set; }
}

public class ExecuteJavascriptArgs
{
    [Required]
    [Description("JavaScript code to execute in the page context. Use 'return' for expressions or write a function body.")]
    public string Script { get; set; }
}
