using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace HQ.Plugins.HubSpot.Models;

/// <summary>
/// Per-tool argument types. Each is the single source of truth for both the LLM-facing schema
/// (generated by <c>ToolSchemaGenerator</c> from these properties/attributes) and the runtime
/// binding target. Camel-cased property names match the LLM-facing parameter names.
/// </summary>

public class CreateContactArgs
{
    [Required]
    [Description("Contact email address")]
    public string Email { get; set; }

    [Description("First name")]
    public string FirstName { get; set; }

    [Description("Last name")]
    public string LastName { get; set; }

    [Description("Company name")]
    public string Company { get; set; }

    [Description("Job title")]
    public string JobTitle { get; set; }

    [Description("Phone number")]
    public string Phone { get; set; }

    [Description("LinkedIn profile URL")]
    public string LinkedInUrl { get; set; }

    [Description("Lifecycle stage: subscriber, lead, opportunity, customer")]
    public string LifecycleStage { get; set; }
}

public class UpdateContactArgs
{
    [Required]
    [Description("The HubSpot contact ID")]
    public string ContactId { get; set; }

    [Description("Updated email address")]
    public string Email { get; set; }

    [Description("Updated first name")]
    public string FirstName { get; set; }

    [Description("Updated last name")]
    public string LastName { get; set; }

    [Description("Updated company name")]
    public string Company { get; set; }

    [Description("Updated job title")]
    public string JobTitle { get; set; }

    [Description("Updated phone number")]
    public string Phone { get; set; }

    [Description("Updated LinkedIn profile URL")]
    public string LinkedInUrl { get; set; }

    [Description("Updated lifecycle stage: subscriber, lead, opportunity, customer")]
    public string LifecycleStage { get; set; }
}

public class SearchContactsArgs
{
    [Required]
    [Description("Search query (searches across name, email, phone, company)")]
    public string Query { get; set; }

    [Description("Maximum results to return (default 10, max 100)")]
    public int? MaxResults { get; set; }

    [Description("Comma-separated property names to return (default: firstname,lastname,email,company,jobtitle,lifecyclestage)")]
    public string Properties { get; set; }
}

public class GetContactArgs
{
    [Required]
    [Description("The HubSpot contact ID")]
    public string ContactId { get; set; }

    [Description("Comma-separated property names to return (default: all standard properties)")]
    public string Properties { get; set; }
}

public class CreateDealArgs
{
    [Required]
    [Description("Name of the deal/opportunity")]
    public string DealName { get; set; }

    [Description("Deal stage: appointmentscheduled, qualifiedtobuy, presentationscheduled, decisionmakerboughtin, contractsent, closedwon, closedlost")]
    public string DealStage { get; set; }

    [Description("Deal value in dollars")]
    public decimal? Amount { get; set; }

    [Description("Expected close date (YYYY-MM-DD)")]
    public string CloseDate { get; set; }

    [Description("Pipeline name (default: 'default')")]
    public string Pipeline { get; set; }

    [Description("Contact ID to associate with this deal")]
    public string ContactId { get; set; }
}

public class UpdateDealArgs
{
    [Required]
    [Description("The HubSpot deal ID")]
    public string DealId { get; set; }

    [Description("Updated deal name")]
    public string DealName { get; set; }

    [Description("Updated deal stage")]
    public string DealStage { get; set; }

    [Description("Updated deal value")]
    public decimal? Amount { get; set; }

    [Description("Updated close date (YYYY-MM-DD)")]
    public string CloseDate { get; set; }

    [Description("Updated pipeline name")]
    public string Pipeline { get; set; }
}

public class SearchDealsArgs
{
    [Description("Search query for deal names")]
    public string Query { get; set; }

    [Description("Filter by deal stage")]
    public string DealStage { get; set; }

    [Description("Filter by pipeline name")]
    public string Pipeline { get; set; }

    [Description("Maximum results to return (default 10, max 100)")]
    public int? MaxResults { get; set; }
}

public class CreateCompanyArgs
{
    [Required]
    [Description("Company name")]
    public string CompanyName { get; set; }

    [Description("Company website domain (e.g. example.com)")]
    public string Domain { get; set; }

    [Description("Industry vertical")]
    public string Industry { get; set; }
}

public class SearchCompaniesArgs
{
    [Required]
    [Description("Search query for company names")]
    public string Query { get; set; }

    [Description("Filter by domain")]
    public string Domain { get; set; }

    [Description("Filter by industry")]
    public string Industry { get; set; }

    [Description("Maximum results to return (default 10, max 100)")]
    public int? MaxResults { get; set; }
}

public class AddNoteArgs
{
    [Required]
    [Description("The note content/body text")]
    public string Notes { get; set; }

    [Required]
    [Description("Object type to attach the note to: contacts, deals, or companies")]
    public string ObjectType { get; set; }

    [Required]
    [Description("The ID of the contact, deal, or company to attach the note to")]
    public string ObjectId { get; set; }
}
