using System.ComponentModel;
using HQ.Models.Helpers;

namespace HQ.Plugins.Weather.Models;

/// <summary>
/// Per-tool argument types. Each is the single source of truth for both the LLM-facing schema
/// (generated by <c>ToolSchemaGenerator</c> from these properties/attributes) and the runtime
/// binding target. Property names match the LLM-facing parameter names.
/// </summary>

public class GetCurrentWeatherArgs
{
    [Description("Place name to geocode, e.g. 'Austin, TX'")]
    public string City { get; set; }

    [Description("Latitude (use with lon instead of city)")]
    public double? Lat { get; set; }

    [Description("Longitude")]
    public double? Lon { get; set; }

    [Description("metric | imperial | standard")]
    public string Units { get; set; }
}

public class GetForecastArgs
{
    [Description("Place name to geocode")]
    public string City { get; set; }

    public double? Lat { get; set; }

    public double? Lon { get; set; }

    [Description("metric | imperial | standard")]
    public string Units { get; set; }

    [Description("Number of forecast days, 1-8 (default 5)")]
    public int? Days { get; set; }
}

public class GetWeatherAlertsArgs
{
    [Description("Place name to geocode")]
    public string City { get; set; }

    public double? Lat { get; set; }

    public double? Lon { get; set; }
}
