using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using HQ.Models.Helpers;
using HQ.Models.Interfaces;

namespace HQ.Plugins.Shopify.Models;

/// <summary>
/// Per-tool argument types. Each is the single source of truth for both the LLM-facing schema
/// (generated by <c>ToolSchemaGenerator</c> from these properties/attributes) and the runtime
/// binding target. Camel-cased property names match the LLM-facing parameter names. Tools that
/// drive a confirmation flow implement <see cref="IPluginServiceRequest"/> so the request envelope
/// survives the confirmation replay round-trip; their framework fields are <c>[Injected]</c>.
/// </summary>

/// <summary>Args for tools that take no LLM parameters (advertises an empty object schema).</summary>
public class EmptyArgs;

public class ListProductsArgs
{
    [Description("Max results (default 50)")]
    public int? Limit { get; set; }
}

public class GetProductArgs
{
    [Required]
    [JsonConverter(typeof(StringOrNumberConverter))]
    public string ProductId { get; set; }
}

public class CreateProductArgs : IPluginServiceRequest
{
    [Injected] public string Method { get; set; }
    [Injected] public string ToolCallId { get; set; }
    [Injected] public string RequestingService { get; set; }
    [Injected] public string ConfirmationId { get; set; }

    [Required]
    public string Title { get; set; }

    [Description("Product description (HTML)")]
    public string BodyHtml { get; set; }

    public string Vendor { get; set; }

    public string ProductType { get; set; }

    [Description("Variant price")]
    public decimal? Price { get; set; }
}

public class UpdateInventoryArgs : IPluginServiceRequest
{
    [Injected] public string Method { get; set; }
    [Injected] public string ToolCallId { get; set; }
    [Injected] public string RequestingService { get; set; }
    [Injected] public string ConfirmationId { get; set; }

    [Required]
    [JsonConverter(typeof(StringOrNumberConverter))]
    public string InventoryItemId { get; set; }

    [Required]
    [JsonConverter(typeof(StringOrNumberConverter))]
    public string LocationId { get; set; }

    [Required]
    [Description("New available quantity")]
    public int? Available { get; set; }
}

public class ListOrdersArgs
{
    [Description("Max results (default 50)")]
    public int? Limit { get; set; }
}

public class GetOrderArgs
{
    [Required]
    [JsonConverter(typeof(StringOrNumberConverter))]
    public string OrderId { get; set; }
}

public class FulfillOrderArgs : IPluginServiceRequest
{
    [Injected] public string Method { get; set; }
    [Injected] public string ToolCallId { get; set; }
    [Injected] public string RequestingService { get; set; }
    [Injected] public string ConfirmationId { get; set; }

    [Required]
    [JsonConverter(typeof(StringOrNumberConverter))]
    public string OrderId { get; set; }
}

public class ListCustomersArgs
{
    [Description("Max results (default 50)")]
    public int? Limit { get; set; }
}

public class SearchCustomersArgs
{
    [Required]
    [Description("Search query, e.g. 'email:jane@acme.com' or a name")]
    public string Query { get; set; }
}

public class CreateDraftOrderArgs : IPluginServiceRequest
{
    [Injected] public string Method { get; set; }
    [Injected] public string ToolCallId { get; set; }
    [Injected] public string RequestingService { get; set; }
    [Injected] public string ConfirmationId { get; set; }

    [Required]
    [Description("Line item title")]
    public string Title { get; set; }

    [Required]
    public decimal? Price { get; set; }

    [Description("Customer email (optional)")]
    public string Email { get; set; }
}
