using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using HQ.Models.Helpers;

namespace HQ.Plugins.Slack.Models;

/// <summary>
/// Per-tool argument types. Each is the single source of truth for both the LLM-facing schema
/// (generated by <c>ToolSchemaGenerator</c> from these properties/attributes) and the runtime
/// binding target. Camel-cased property names match the LLM-facing parameter names.
/// </summary>

/// <summary>Args for tools that take no LLM parameters (advertises an empty object schema).</summary>
public class EmptyArgs;

public class SendSlackMessageArgs
{
    [Description("The Slack channel or DM ID to send the message to. Optional, defaults to configured notification channel.")]
    public string ChannelId { get; set; }

    [Required]
    [Description("The message text to send")]
    public string MessageText { get; set; }

    /// <summary>Alias for MessageText — some LLMs send "message". Hidden from the schema, still bound.</summary>
    [Injected]
    [JsonPropertyName("message")]
    public string Message { set => MessageText ??= value; get => null; }

    [Description("Optional base64-encoded file content to attach")]
    public string FileContent { get; set; }

    [Description("Optional filename for the attachment")]
    public string FileName { get; set; }

    [Description("Optional MIME type for the attachment")]
    public string FileType { get; set; }
}

public class UploadSlackFileArgs
{
    [Required]
    [Description("The Slack channel ID to upload the file to")]
    public string ChannelId { get; set; }

    [Required]
    [Description("Base64-encoded file content")]
    public string FileContent { get; set; }

    [Required]
    [Description("The filename")]
    public string FileName { get; set; }

    [Description("Optional MIME type for the file")]
    public string FileType { get; set; }
}

public class DownloadSlackFileArgs
{
    [Required]
    [Description("The Slack file ID (starts with F)")]
    public string FileId { get; set; }
}

public class OpenSlackDmArgs
{
    [Required]
    [Description("Comma-separated Slack user IDs to open a DM with")]
    public string UserIds { get; set; }
}
