namespace HQ.Plugins.Tests.Conventions;

/// <summary>
/// SAFE-02 manifest: every plugin in this repo must be categorized here. Plugins that
/// return externally-authored content (web pages, emails, inbound messages, third-party
/// user-generated text) must wrap those fields in <c>Untrusted&lt;T&gt;</c> so the host's
/// ToolResultSanitizer can classify them before they reach an agent's LLM — and must ship
/// a <c>{Name}ProvenanceTests</c> class proving it. The convention tests fail the build
/// when a new plugin is added without a category, or a wrapped plugin loses its tests.
/// </summary>
public static class ExternalContentManifest
{
    /// <summary>
    /// Plugins whose external-content return fields are wrapped as Untrusted&lt;T&gt;.
    /// Each MUST have a {ShortName}ProvenanceTests class in this test project.
    /// </summary>
    public static readonly IReadOnlySet<string> WrappedExternalContent = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        // Open web / search — arbitrary attacker-controlled pages and results
        "HQ.Plugins.WebReader",
        "HQ.Plugins.WebSearch",
        "HQ.Plugins.HeadlessBrowser",
        "HQ.Plugins.Perplexity",
        // Email — sender-controlled subject/body/preview
        "HQ.Plugins.Email",
        // Inbound human-authored messages
        "HQ.Plugins.Slack",
        "HQ.Plugins.Teams",
        "HQ.Plugins.Telegram",
        "HQ.Plugins.Twilio",
        "HQ.Plugins.Zendesk",
        "HQ.Plugins.SupportChannelKb",
        // SaaS user-generated content (issue/task/page bodies, comments, profiles)
        "HQ.Plugins.Jira",
        "HQ.Plugins.Asana",
        "HQ.Plugins.Notion",
        "HQ.Plugins.LinkedIn",
        "HQ.Plugins.HubSpot",
        "HQ.Plugins.UseMemos",
        "HQ.Plugins.GoogleContacts",
        "HQ.Plugins.GoogleForms",
        "HQ.Plugins.GoogleWorkspace",
        "HQ.Plugins.GoogleCalendar",
        "HQ.Plugins.Microsoft365",
        "HQ.Plugins.DocumentAI",
    };

    /// <summary>
    /// Plugins exempt from wrapping, with the reason. Mostly structured vendor-API data
    /// (ids, amounts, enums) or content the agent's own org authored. Free-text fields in
    /// these (customer names, memos) are low-volume and low-risk; promote a plugin to
    /// WrappedExternalContent if that judgment changes.
    /// </summary>
    public static readonly IReadOnlySet<string> InternalOrStructured = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "HQ.Plugins.Calendly",          // own scheduling links/events; invitee fields are structured
        "HQ.Plugins.ClaudeCode",        // local tool output, not third-party content
        "HQ.Plugins.DocuSign",          // envelope status/metadata, own documents
        "HQ.Plugins.FileStorage",       // own stored files
        "HQ.Plugins.GoogleAnalytics",   // numeric metrics/dimensions
        "HQ.Plugins.Gusto",             // structured payroll data from vendor API
        "HQ.Plugins.Health",            // own health metrics
        "HQ.Plugins.HomeAssistantAssist", // own home automation states
        "HQ.Plugins.ImageGeneration",   // generated by own request; returns file refs
        "HQ.Plugins.Mailchimp",         // own campaigns/audiences (org-authored)
        "HQ.Plugins.Maps",              // structured geo data from vendor API
        "HQ.Plugins.Plaid",             // structured financial data
        "HQ.Plugins.QuickBooks",        // structured accounting data
        "HQ.Plugins.Ramp",              // structured spend data
        "HQ.Plugins.ReportGenerator",   // renders agent-authored content
        "HQ.Plugins.Shopify",           // structured commerce data (order notes are low-risk)
        "HQ.Plugins.Square",            // structured payments data
        "HQ.Plugins.Stripe",            // structured payments data
        "HQ.Plugins.Tasks",             // own task store (agent/org-authored)
        "HQ.Plugins.Weather",           // structured weather data
    };
}
