using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace HQ.Plugins.Teams.Models;

/// <summary>
/// Per-tool argument types. Each is the single source of truth for both the LLM-facing schema
/// (generated by <c>ToolSchemaGenerator</c> from these properties/attributes) and the runtime
/// binding target. Camel-cased property names match the LLM-facing parameter names.
/// </summary>

/// <summary>Args for tools that take no LLM parameters (advertises an empty object schema).</summary>
public class EmptyArgs;

public class SendTeamsMessageArgs
{
    [Required, Description("The message text to send")]
    public string MessageText { get; set; }

    [Description("The Teams team ID. Optional, defaults to configured notification team.")]
    public string TeamId { get; set; }

    [Description("The Teams channel ID. Optional, defaults to configured notification channel.")]
    public string ChannelId { get; set; }
}

public class ListTeamsChannelsArgs
{
    [Required, Description("The Teams team ID to list channels for")]
    public string TeamId { get; set; }
}

public class SendTeamsFileArgs
{
    [Required, Description("The Teams team ID")]
    public string TeamId { get; set; }

    [Required, Description("The Teams channel ID")]
    public string ChannelId { get; set; }

    [Required, Description("Base64-encoded file content")]
    public string FileContent { get; set; }

    [Required, Description("The filename")]
    public string FileName { get; set; }

    [Description("Optional MIME type for the file")]
    public string FileType { get; set; }
}

public class DownloadTeamsFileArgs
{
    [Required, Description("The drive item ID in format 'driveId/itemId'")]
    public string DriveItemId { get; set; }
}
