using System.ComponentModel;

namespace HQ.Plugins.Plaid.Models;

/// <summary>
/// Per-tool argument types. Each is the single source of truth for both the LLM-facing schema
/// (generated by <c>ToolSchemaGenerator</c> from these properties/attributes) and the runtime
/// binding target. Camel-cased property names match the LLM-facing parameter names.
/// </summary>

/// <summary>Args for <c>list_accounts</c>.</summary>
public class ListAccountsArgs
{
    [Description("Optional item access_token override")]
    public string AccessToken { get; set; }
}

/// <summary>Args for <c>get_balances</c>.</summary>
public class GetBalancesArgs
{
    [Description("Optional item access_token override")]
    public string AccessToken { get; set; }
}

/// <summary>Args for <c>list_transactions</c>.</summary>
public class ListTransactionsArgs
{
    [Description("YYYY-MM-DD (default 30 days ago)")]
    public string StartDate { get; set; }

    [Description("YYYY-MM-DD (default today)")]
    public string EndDate { get; set; }

    [Description("Max results (default 100, max 500)")]
    public int? Count { get; set; }

    [Description("Pagination offset")]
    public int? Offset { get; set; }

    [Description("Optional item access_token override")]
    public string AccessToken { get; set; }
}
