using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace HQ.Plugins.Health.Models;

/// <summary>
/// Per-tool argument types. Each is the single source of truth for both the LLM-facing schema
/// (generated by <c>ToolSchemaGenerator</c> from these properties/attributes) and the runtime
/// binding target. Camel-cased property names match the LLM-facing parameter names.
/// </summary>

/// <summary>Args for tools that take no LLM parameters (advertises an empty object schema).</summary>
public class EmptyArgs;

/// <summary>Args for <c>get_sleep</c> — a connected user and an optional date window.</summary>
public class GetSleepArgs
{
    [Required]
    public string UserId { get; set; }

    [Description("YYYY-MM-DD (default 7 days ago)")]
    public string StartDate { get; set; }

    [Description("YYYY-MM-DD (default today)")]
    public string EndDate { get; set; }
}

/// <summary>Args for <c>get_activity</c> — a connected user and an optional date window.</summary>
public class GetActivityArgs
{
    [Required]
    public string UserId { get; set; }

    [Description("YYYY-MM-DD (default 7 days ago)")]
    public string StartDate { get; set; }

    [Description("YYYY-MM-DD (default today)")]
    public string EndDate { get; set; }
}

/// <summary>Args for <c>get_daily</c> — a connected user and an optional date window.</summary>
public class GetDailyArgs
{
    [Required]
    public string UserId { get; set; }

    [Description("YYYY-MM-DD (default 7 days ago)")]
    public string StartDate { get; set; }

    [Description("YYYY-MM-DD (default today)")]
    public string EndDate { get; set; }
}

/// <summary>Args for <c>get_body</c> — a connected user and an optional date window.</summary>
public class GetBodyArgs
{
    [Required]
    public string UserId { get; set; }

    [Description("YYYY-MM-DD (default 7 days ago)")]
    public string StartDate { get; set; }

    [Description("YYYY-MM-DD (default today)")]
    public string EndDate { get; set; }
}
